# GPIO Pins
ENCODER_BUTTON_PIN = 29
ENCODER_CLK_PIN = 30
ENCODER_DT_PIN = 31

# Display Pins
DISPLAY_RST_PIN = 24
DISPLAY_DC_PIN = 23
DISPLAY_SPI_PORT = 0
DISPLAY_SPI_DEVICE = 0

# Display Properties
DISPLAY_WIDTH = 128
DISPLAY_HEIGHT = 32
DISPLAY_SPI_SPEED = 8000000
