# GPIO Pins
RECORD_BUTTON_PIN = 5;
RECORD_LED_PIN = 6;

ENCODER_BUTTON_PIN = 17;
ENCODER_CLK_PIN = 27;
ENCODER_DT_PIN = 22;

# Display Pins
DISPLAY_RST_PIN = 24;
DISPLAY_DC_PIN = 23;
DISPLAY_SPI_PORT = 0;
DISPLAY_SPI_DEVICE = 0;

# Display Properties
DISPLAY_WIDTH = 128
DISPLAY_HEIGHT = 32
